# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Venv_Projects/TurkeyMap/design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IS(object):
    def setupUi(self, IS):
        IS.setObjectName("IS")
        IS.resize(1900, 1025)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IS.sizePolicy().hasHeightForWidth())
        IS.setSizePolicy(sizePolicy)
        IS.setMinimumSize(QtCore.QSize(580, 750))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/Esat Can/Desktop/eko.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IS.setWindowIcon(icon)
        IS.setAutoFillBackground(False)
        IS.setStyleSheet("")
        IS.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(IS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("font-size:18px;\n"
"background-color: rgba(67, 99, 125, 255)")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("border:none;font-size:25px; color:#fff")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_3.setGeometry(QtCore.QRect(-730, 560, 401, 161))
        self.groupBox_3.setStyleSheet("color: rgb(255, 255, 255);border-radius: 8px;")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.image_UAV_2 = QtWidgets.QLabel(self.groupBox_3)
        self.image_UAV_2.setGeometry(QtCore.QRect(20, 0, 81, 41))
        self.image_UAV_2.setStyleSheet("image: url(\'./img/gps.png\');")
        self.image_UAV_2.setText("")
        self.image_UAV_2.setObjectName("image_UAV_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 401, 111))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.enlem_lbl_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.enlem_lbl_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.enlem_lbl_2.setFont(font)
        self.enlem_lbl_2.setAutoFillBackground(False)
        self.enlem_lbl_2.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.enlem_lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enlem_lbl_2.setObjectName("enlem_lbl_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.enlem_lbl_2)
        self.veritext_Enlem = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.veritext_Enlem.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.veritext_Enlem.setFont(font)
        self.veritext_Enlem.setAutoFillBackground(False)
        self.veritext_Enlem.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.veritext_Enlem.setAlignment(QtCore.Qt.AlignCenter)
        self.veritext_Enlem.setObjectName("veritext_Enlem")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.veritext_Enlem)
        self.enlem_lbl_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.enlem_lbl_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.enlem_lbl_5.setFont(font)
        self.enlem_lbl_5.setAutoFillBackground(False)
        self.enlem_lbl_5.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.enlem_lbl_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enlem_lbl_5.setObjectName("enlem_lbl_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.enlem_lbl_5)
        self.veritext_Boylam = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.veritext_Boylam.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.veritext_Boylam.setFont(font)
        self.veritext_Boylam.setAutoFillBackground(False)
        self.veritext_Boylam.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.veritext_Boylam.setAlignment(QtCore.Qt.AlignCenter)
        self.veritext_Boylam.setObjectName("veritext_Boylam")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.veritext_Boylam)
        self.enlem_lbl_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.enlem_lbl_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.enlem_lbl_9.setFont(font)
        self.enlem_lbl_9.setAutoFillBackground(False)
        self.enlem_lbl_9.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.enlem_lbl_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enlem_lbl_9.setObjectName("enlem_lbl_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.enlem_lbl_9)
        self.veritext_Saat = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.veritext_Saat.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.veritext_Saat.setFont(font)
        self.veritext_Saat.setAutoFillBackground(False)
        self.veritext_Saat.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.veritext_Saat.setAlignment(QtCore.Qt.AlignCenter)
        self.veritext_Saat.setObjectName("veritext_Saat")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.veritext_Saat)
        self.widget_4 = QtWidgets.QWidget(self.tab_7)
        self.widget_4.setGeometry(QtCore.QRect(10, 0, 1871, 971))
        self.widget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_4.setStyleSheet("background:  url(\'./img/bg.jpg\') no-repeat ;")
        self.widget_4.setObjectName("widget_4")
        self.cbox_sehir = QtWidgets.QComboBox(self.widget_4)
        self.cbox_sehir.setGeometry(QtCore.QRect(390, 100, 851, 61))
        self.cbox_sehir.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.cbox_sehir.setAcceptDrops(False)
        self.cbox_sehir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbox_sehir.setStyleSheet("background: rgba(74,112,139,255);color:white;float:right;font-size:34px;border-radius: 15px;")
        self.cbox_sehir.setEditable(False)
        self.cbox_sehir.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.cbox_sehir.setModelColumn(0)
        self.cbox_sehir.setObjectName("cbox_sehir")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.btn_Getir = QtWidgets.QPushButton(self.widget_4)
        self.btn_Getir.setGeometry(QtCore.QRect(1260, 100, 321, 61))
        self.btn_Getir.setStyleSheet("background-color:gray;border-radius: 22px;color:white;\n"
"")
        self.btn_Getir.setObjectName("btn_Getir")
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox.setGeometry(QtCore.QRect(350, 220, 1191, 721))
        self.groupBox.setStyleSheet("background-color: rgba(74,112,139,255);border-radius:24px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lbl_sehir = QtWidgets.QLabel(self.groupBox)
        self.lbl_sehir.setGeometry(QtCore.QRect(10, 70, 1171, 141))
        self.lbl_sehir.setStyleSheet("font-size:80px;")
        self.lbl_sehir.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sehir.setObjectName("lbl_sehir")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 350, 1121, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("font-size:50px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("font-size:50px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("font-size:50px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("font-size:50px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lbl_nufus = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_nufus.setStyleSheet("font-size:50px;")
        self.lbl_nufus.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_nufus.setObjectName("lbl_nufus")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_nufus)
        self.lbl_katki = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_katki.setStyleSheet("font-size:50px;")
        self.lbl_katki.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_katki.setObjectName("lbl_katki")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_katki)
        self.lbl_katkiyuzde = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_katkiyuzde.setStyleSheet("font-size:50px;")
        self.lbl_katkiyuzde.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_katkiyuzde.setObjectName("lbl_katkiyuzde")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_katkiyuzde)
        self.lbl_gelir = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_gelir.setStyleSheet("font-size:50px;")
        self.lbl_gelir.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gelir.setObjectName("lbl_gelir")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_gelir)
        self.frame_5 = QtWidgets.QFrame(self.groupBox)
        self.frame_5.setGeometry(QtCore.QRect(370, 70, 441, 141))
        self.frame_5.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.groupBox)
        self.frame_6.setGeometry(QtCore.QRect(10, 280, 1171, 431))
        self.frame_6.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(400, 370, 441, 41))
        self.label_9.setObjectName("label_9")
        self.pb_katki = QtWidgets.QProgressBar(self.widget_4)
        self.pb_katki.setGeometry(QtCore.QRect(30, 230, 311, 701))
        self.pb_katki.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.pb_katki.setProperty("value", 0)
        self.pb_katki.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_katki.setOrientation(QtCore.Qt.Vertical)
        self.pb_katki.setObjectName("pb_katki")
        self.pb_nufus = QtWidgets.QProgressBar(self.widget_4)
        self.pb_nufus.setGeometry(QtCore.QRect(1550, 230, 311, 701))
        self.pb_nufus.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.pb_nufus.setProperty("value", 0)
        self.pb_nufus.setAlignment(QtCore.Qt.AlignCenter)
        self.pb_nufus.setOrientation(QtCore.Qt.Vertical)
        self.pb_nufus.setObjectName("pb_nufus")
        self.widget_4.raise_()
        self.groupBox_3.raise_()
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_5 = QtWidgets.QWidget(self.tab_5)
        self.widget_5.setGeometry(QtCore.QRect(320, 60, 1280, 811))
        self.widget_5.setObjectName("widget_5")
        self.frame_7 = QtWidgets.QFrame(self.widget_5)
        self.frame_7.setGeometry(QtCore.QRect(230, 10, 821, 211))
        self.frame_7.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(40, 40, 761, 131))
        self.label.setStyleSheet("font-size:80px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.widget_5)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(290, 700, 722, 78))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_2.setStyleSheet("font-size:50px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lbl_manGelir = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_manGelir.setStyleSheet("font-size:50px;")
        self.lbl_manGelir.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_manGelir.setObjectName("lbl_manGelir")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_manGelir)
        self.frame_8 = QtWidgets.QFrame(self.widget_5)
        self.frame_8.setGeometry(QtCore.QRect(230, 230, 831, 261))
        self.frame_8.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.edt_Gelir = QtWidgets.QLineEdit(self.frame_8)
        self.edt_Gelir.setGeometry(QtCore.QRect(500, 40, 281, 71))
        self.edt_Gelir.setStyleSheet("background-color:white;border-radius:24px;color:black;")
        self.edt_Gelir.setAlignment(QtCore.Qt.AlignCenter)
        self.edt_Gelir.setObjectName("edt_Gelir")
        self.edt_nufus = QtWidgets.QLineEdit(self.frame_8)
        self.edt_nufus.setGeometry(QtCore.QRect(500, 150, 281, 71))
        self.edt_nufus.setStyleSheet("background-color:white;border-radius:24px;color:black;")
        self.edt_nufus.setAlignment(QtCore.Qt.AlignCenter)
        self.edt_nufus.setObjectName("edt_nufus")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(90, 160, 387, 60))
        self.label_8.setStyleSheet("font-size:50px;border-radius:18px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(90, 50, 387, 60))
        self.label_7.setStyleSheet("font-size:50px;border-radius:18px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_9 = QtWidgets.QFrame(self.widget_5)
        self.frame_9.setGeometry(QtCore.QRect(250, 670, 801, 131))
        self.frame_9.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.btn_Hesapla = QtWidgets.QPushButton(self.widget_5)
        self.btn_Hesapla.setGeometry(QtCore.QRect(600, 540, 201, 81))
        self.btn_Hesapla.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.btn_Hesapla.setObjectName("btn_Hesapla")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        IS.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(IS)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(IS)
        self.tabWidget.setCurrentIndex(0)
        self.cbox_sehir.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IS)

    def retranslateUi(self, IS):
        _translate = QtCore.QCoreApplication.translate
        IS.setWindowTitle(_translate("IS", "Income Status"))
        self.groupBox_3.setTitle(_translate("IS", "GPS"))
        self.enlem_lbl_2.setText(_translate("IS", "ENLEM :"))
        self.veritext_Enlem.setText(_translate("IS", "88"))
        self.enlem_lbl_5.setText(_translate("IS", "BOYLAM:"))
        self.veritext_Boylam.setText(_translate("IS", "88"))
        self.enlem_lbl_9.setText(_translate("IS", "GPS SAATİ:"))
        self.veritext_Saat.setText(_translate("IS", "88"))
        self.cbox_sehir.setCurrentText(_translate("IS", "ADANA"))
        self.cbox_sehir.setItemText(0, _translate("IS", "ADANA"))
        self.cbox_sehir.setItemText(1, _translate("IS", "ADIYAMAN"))
        self.cbox_sehir.setItemText(2, _translate("IS", "AFYON"))
        self.cbox_sehir.setItemText(3, _translate("IS", "AĞRI"))
        self.cbox_sehir.setItemText(4, _translate("IS", "AMASYA"))
        self.cbox_sehir.setItemText(5, _translate("IS", "ANKARA"))
        self.cbox_sehir.setItemText(6, _translate("IS", "ANTALYA"))
        self.cbox_sehir.setItemText(7, _translate("IS", "ARTVİN"))
        self.cbox_sehir.setItemText(8, _translate("IS", "AYDIN"))
        self.cbox_sehir.setItemText(9, _translate("IS", "BALIKESİR"))
        self.cbox_sehir.setItemText(10, _translate("IS", "BİLECİK"))
        self.cbox_sehir.setItemText(11, _translate("IS", "BİNGÖL"))
        self.cbox_sehir.setItemText(12, _translate("IS", "BİTLİS"))
        self.cbox_sehir.setItemText(13, _translate("IS", "BOLU"))
        self.cbox_sehir.setItemText(14, _translate("IS", "BURDUR"))
        self.cbox_sehir.setItemText(15, _translate("IS", "BURSA"))
        self.cbox_sehir.setItemText(16, _translate("IS", "ÇANAKKALE"))
        self.cbox_sehir.setItemText(17, _translate("IS", "ÇANKIRI"))
        self.cbox_sehir.setItemText(18, _translate("IS", "ÇORUM"))
        self.cbox_sehir.setItemText(19, _translate("IS", "DENİZLİ"))
        self.cbox_sehir.setItemText(20, _translate("IS", "DİYARBAKIR"))
        self.cbox_sehir.setItemText(21, _translate("IS", "EDİRNE"))
        self.cbox_sehir.setItemText(22, _translate("IS", "ELAZIĞ"))
        self.cbox_sehir.setItemText(23, _translate("IS", "ERZİNCAN"))
        self.cbox_sehir.setItemText(24, _translate("IS", "ERZURUM"))
        self.cbox_sehir.setItemText(25, _translate("IS", "ESKİŞEHİR"))
        self.cbox_sehir.setItemText(26, _translate("IS", "GAZİANTEP"))
        self.cbox_sehir.setItemText(27, _translate("IS", "GİRESUN"))
        self.cbox_sehir.setItemText(28, _translate("IS", "GÜMÜŞHANE"))
        self.cbox_sehir.setItemText(29, _translate("IS", "HAKKARİ"))
        self.cbox_sehir.setItemText(30, _translate("IS", "HATAY"))
        self.cbox_sehir.setItemText(31, _translate("IS", "ISPARTA"))
        self.cbox_sehir.setItemText(32, _translate("IS", "MERSİN"))
        self.cbox_sehir.setItemText(33, _translate("IS", "İSTANBUL"))
        self.cbox_sehir.setItemText(34, _translate("IS", "İZMİR"))
        self.cbox_sehir.setItemText(35, _translate("IS", "KARS"))
        self.cbox_sehir.setItemText(36, _translate("IS", "KASTAMONU"))
        self.cbox_sehir.setItemText(37, _translate("IS", "KAYSERİ"))
        self.cbox_sehir.setItemText(38, _translate("IS", "KIRKLARELİ"))
        self.cbox_sehir.setItemText(39, _translate("IS", "KIRŞEHİR"))
        self.cbox_sehir.setItemText(40, _translate("IS", "KOCAELİ"))
        self.cbox_sehir.setItemText(41, _translate("IS", "KONYA"))
        self.cbox_sehir.setItemText(42, _translate("IS", "KÜTAHYA"))
        self.cbox_sehir.setItemText(43, _translate("IS", "MALATYA"))
        self.cbox_sehir.setItemText(44, _translate("IS", "MANİSA"))
        self.cbox_sehir.setItemText(45, _translate("IS", "KAHRAMANMARAŞ"))
        self.cbox_sehir.setItemText(46, _translate("IS", "MARDİN"))
        self.cbox_sehir.setItemText(47, _translate("IS", "MUĞLA"))
        self.cbox_sehir.setItemText(48, _translate("IS", "MUŞ"))
        self.cbox_sehir.setItemText(49, _translate("IS", "NEVŞEHİR"))
        self.cbox_sehir.setItemText(50, _translate("IS", "NİĞDE"))
        self.cbox_sehir.setItemText(51, _translate("IS", "ORDU"))
        self.cbox_sehir.setItemText(52, _translate("IS", "RİZE"))
        self.cbox_sehir.setItemText(53, _translate("IS", "SAKARYA"))
        self.cbox_sehir.setItemText(54, _translate("IS", "SAMSUN"))
        self.cbox_sehir.setItemText(55, _translate("IS", "SİVAS"))
        self.cbox_sehir.setItemText(56, _translate("IS", "SİİRT"))
        self.cbox_sehir.setItemText(57, _translate("IS", "SİNOP"))
        self.cbox_sehir.setItemText(58, _translate("IS", "TEKİRDAĞ"))
        self.cbox_sehir.setItemText(59, _translate("IS", "TOKAT"))
        self.cbox_sehir.setItemText(60, _translate("IS", "TRABZON"))
        self.cbox_sehir.setItemText(61, _translate("IS", "TUNCELİ"))
        self.cbox_sehir.setItemText(62, _translate("IS", "ŞANLIURFA"))
        self.cbox_sehir.setItemText(63, _translate("IS", "UŞAK"))
        self.cbox_sehir.setItemText(64, _translate("IS", "VAN"))
        self.cbox_sehir.setItemText(65, _translate("IS", "YOZGAT"))
        self.cbox_sehir.setItemText(66, _translate("IS", "ZONGULDAK"))
        self.cbox_sehir.setItemText(67, _translate("IS", "AKSARAY"))
        self.cbox_sehir.setItemText(68, _translate("IS", "BAYBURT"))
        self.cbox_sehir.setItemText(69, _translate("IS", "KARAMAN"))
        self.cbox_sehir.setItemText(70, _translate("IS", "KIRIKKALE"))
        self.cbox_sehir.setItemText(71, _translate("IS", "BATMAN"))
        self.cbox_sehir.setItemText(72, _translate("IS", "ŞIRNAK"))
        self.cbox_sehir.setItemText(73, _translate("IS", "BARTIN"))
        self.cbox_sehir.setItemText(74, _translate("IS", "ARDAHAN"))
        self.cbox_sehir.setItemText(75, _translate("IS", "IĞDIR"))
        self.cbox_sehir.setItemText(76, _translate("IS", "YALOVA"))
        self.cbox_sehir.setItemText(77, _translate("IS", "KARABÜK"))
        self.cbox_sehir.setItemText(78, _translate("IS", "KİLİS"))
        self.cbox_sehir.setItemText(79, _translate("IS", "OSMANİYE"))
        self.cbox_sehir.setItemText(80, _translate("IS", "DÜZCE"))
        self.btn_Getir.setToolTip(_translate("IS", "İstenilen Şehrin Özelliklerini Getirir"))
        self.btn_Getir.setText(_translate("IS", "GETİR"))
        self.lbl_sehir.setText(_translate("IS", "ŞEHİR"))
        self.label_4.setText(_translate("IS", "KATKI YÜZDESİ:"))
        self.label_5.setText(_translate("IS", "ÜLKEYE KATKISI:"))
        self.label_3.setText(_translate("IS", "NÜFUS:"))
        self.label_6.setText(_translate("IS", "KİŞİ BAŞI GELİR:"))
        self.lbl_nufus.setText(_translate("IS", "000"))
        self.lbl_katki.setText(_translate("IS", "000"))
        self.lbl_katkiyuzde.setText(_translate("IS", "000"))
        self.lbl_gelir.setText(_translate("IS", "000"))
        self.label_9.setText(_translate("IS", "*DEĞERLERİN TAMAMI YIL BAZLIDIR*"))
        self.pb_katki.setFormat(_translate("IS", "ŞEHRİN ÜLKEYE KATKISI"))
        self.pb_nufus.setFormat(_translate("IS", "NÜFUS "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("IS", "ŞEHİRLER"))
        self.label.setText(_translate("IS", "KENDİN HESAPLA"))
        self.label_2.setText(_translate("IS", "KİŞİ BAŞI GELİR:"))
        self.lbl_manGelir.setText(_translate("IS", "000"))
        self.edt_Gelir.setPlaceholderText(_translate("IS", "BURAYA YAZINIZ"))
        self.edt_nufus.setPlaceholderText(_translate("IS", "BURAYA YAZINIZ"))
        self.label_8.setText(_translate("IS", "NÜFUS SAYISI:"))
        self.label_7.setText(_translate("IS", "ŞEHİR GELİRİ:"))
        self.btn_Hesapla.setText(_translate("IS", "HESAPLA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("IS", "KENDİN HESAPLA"))
        self.actionExit.setText(_translate("IS", "Exit"))

